name: 'VS Code Server Action'
author: 'christian-bromann'
description: 'A GitHub Action that allows to debug GitHub workflows using VS Code'
inputs:
  machineName:
    description: 'Name of the machine to access (default: GitHub Action run id)'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'target'  
  color: 'blue'