name: "CI"
on:
  push:
    branches: [ cb-test ]
  pull_request:
    branches: [ cb-test ]
  schedule:
    - cron: '22 12 * * 0'
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - uses: ./
    # - name: Setup Node
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: "16"
    # - name: Install
    #   run: yarn install --frozen-lockfile
    # - name: Lint
    #   run: yarn run lint:check
